import 'package:recipe_book/models/recipe_model.dart';

class RecipeRepository {
  static List<Recipe> getRecipes() {
    return [
      Recipe(
        id: '1',
        name: 'Spaghetti Carbonara',
        category: 'Italian',
        difficulty: 'Medium',
        time: '30 mins',
        servings: '4',
        description: 'Classic Italian pasta dish with eggs, cheese, and bacon.',
        imageEmoji: '🍝',
        ingredients: [
          '400g spaghetti',
          '200g pancetta or bacon',
          '4 large eggs',
          '100g Parmesan cheese',
          '2 cloves garlic',
          'Black pepper',
          'Salt',
        ],
        instructions: [
          'Bring a large pot of salted water to boil and cook spaghetti according to package directions.',
          'While pasta cooks, fry pancetta until crispy in a large pan.',
          'Beat eggs with grated Parmesan cheese in a bowl.',
          'Drain pasta, reserving 1 cup of pasta water.',
          'Add hot pasta to pancetta pan, remove from heat.',
          'Quickly stir in egg mixture, adding pasta water to create creamy sauce.',
          'Season with black pepper and serve immediately.',
        ],
      ),
      Recipe(
        id: '2',
        name: 'Chicken Tikka Masala',
        category: 'Indian',
        difficulty: 'Hard',
        time: '60 mins',
        servings: '6',
        description: 'Creamy and flavorful Indian curry with tender chicken.',
        imageEmoji: '🍛',
        ingredients: [
          '800g chicken breast',
          '1 cup yogurt',
          '400ml coconut milk',
          '400g crushed tomatoes',
          '3 tbsp tikka masala paste',
          '1 onion, diced',
          '3 cloves garlic',
          '1 inch ginger',
          'Fresh cilantro',
          'Rice for serving',
        ],
        instructions: [
          'Marinate chicken in yogurt and half the tikka paste for 30 minutes.',
          'Heat oil in a large pan and cook chicken until golden. Set aside.',
          'In the same pan, sauté onion, garlic, and ginger until soft.',
          'Add remaining tikka paste and cook for 2 minutes.',
          'Pour in crushed tomatoes and coconut milk. Simmer for 10 minutes.',
          'Return chicken to pan and cook for another 10 minutes.',
          'Garnish with fresh cilantro and serve with rice.',
        ],
      ),
      Recipe(
        id: '3',
        name: 'Caesar Salad',
        category: 'Salad',
        difficulty: 'Easy',
        time: '15 mins',
        servings: '4',
        description: 'Fresh and crispy salad with homemade Caesar dressing.',
        imageEmoji: '🥗',
        ingredients: [
          '2 romaine lettuce heads',
          '100g Parmesan cheese',
          '1 cup croutons',
          '2 cloves garlic',
          '2 anchovy fillets',
          '1 egg yolk',
          '2 tbsp lemon juice',
          '1/2 cup olive oil',
          'Salt and pepper',
        ],
        instructions: [
          'Wash and chop romaine lettuce into bite-sized pieces.',
          'For dressing: blend garlic, anchovies, egg yolk, and lemon juice.',
          'Slowly drizzle in olive oil while blending until emulsified.',
          'Season dressing with salt and pepper.',
          'Toss lettuce with dressing until well coated.',
          'Top with Parmesan shavings and croutons.',
          'Serve immediately while lettuce is crisp.',
        ],
      ),
      Recipe(
        id: '4',
        name: 'Chocolate Chip Cookies',
        category: 'Dessert',
        difficulty: 'Easy',
        time: '25 mins',
        servings: '24 cookies',
        description: 'Classic homemade cookies with melty chocolate chips.',
        imageEmoji: '🍪',
        ingredients: [
          '2 1/4 cups all-purpose flour',
          '1 cup butter, softened',
          '3/4 cup white sugar',
          '3/4 cup brown sugar',
          '2 eggs',
          '2 tsp vanilla extract',
          '1 tsp baking soda',
          '1 tsp salt',
          '2 cups chocolate chips',
        ],
        instructions: [
          'Preheat oven to 375°F (190°C).',
          'Cream together butter and both sugars until fluffy.',
          'Beat in eggs and vanilla extract.',
          'In separate bowl, combine flour, baking soda, and salt.',
          'Gradually blend dry ingredients into butter mixture.',
          'Stir in chocolate chips.',
          'Drop rounded tablespoons of dough onto ungreased cookie sheets.',
          'Bake for 9-11 minutes or until golden brown.',
          'Cool on baking sheet for 2 minutes before transferring to wire rack.',
        ],
      ),
      Recipe(
        id: '5',
        name: 'Beef Tacos',
        category: 'Mexican',
        difficulty: 'Easy',
        time: '20 mins',
        servings: '4',
        description: 'Quick and delicious tacos with seasoned beef.',
        imageEmoji: '🌮',
        ingredients: [
          '500g ground beef',
          '8 taco shells',
          '1 packet taco seasoning',
          '1 cup shredded lettuce',
          '1 cup diced tomatoes',
          '1 cup shredded cheese',
          '1/2 cup sour cream',
          '1/2 cup salsa',
          '1 onion, diced',
        ],
        instructions: [
          'Brown ground beef in a large skillet over medium heat.',
          'Drain excess fat and add taco seasoning with water as directed.',
          'Simmer for 5 minutes until sauce thickens.',
          'Warm taco shells according to package directions.',
          'Fill each shell with seasoned beef.',
          'Top with lettuce, tomatoes, cheese, sour cream, and salsa.',
          'Serve immediately while hot.',
        ],
      ),
      Recipe(
        id: '6',
        name: 'Greek Salad',
        category: 'Salad',
        difficulty: 'Easy',
        time: '10 mins',
        servings: '4',
        description: 'Fresh Mediterranean salad with feta and olives.',
        imageEmoji: '🥙',
        ingredients: [
          '4 tomatoes, chopped',
          '1 cucumber, sliced',
          '1 red onion, sliced',
          '1 green bell pepper',
          '200g feta cheese',
          '1/2 cup Kalamata olives',
          '1/4 cup olive oil',
          '2 tbsp red wine vinegar',
          'Oregano',
          'Salt and pepper',
        ],
        instructions: [
          'Chop all vegetables into bite-sized pieces.',
          'Place vegetables in a large bowl.',
          'Add olives and crumbled feta cheese.',
          'Whisk together olive oil, vinegar, oregano, salt, and pepper.',
          'Pour dressing over salad and toss gently.',
          'Let sit for 5 minutes to allow flavors to meld.',
          'Serve chilled or at room temperature.',
        ],
      ),
    ];
  }
}
